#!/bin/bash
wget https://zenodo.org/record/7064308/files/test.tar.gz
tar -xzf test.tar.gz -C docs/examples/ClimateBench/
wget https://zenodo.org/record/7064308/files/train_val.tar.gz
tar -xzf train_val.tar.gz -C docs/examples/ClimateBench/
